-- POSTGRES
--CREATE DATABASE lprc5 WITH ENCODING 'Unicode' LC_COLLATE='pt_BR.UTF8' LC_CTYPE='pt_BR.UTF8' TEMPLATE 'template0';

CREATE TABLE IF NOT EXISTS TIPO_FUNCIONARIO (
	T_ID SERIAL PRIMARY KEY,
	T_NOME VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
	DEP_CODIGO SERIAL PRIMARY KEY,
	DEP_SIGLA VARCHAR NOT NULL UNIQUE,
	DEP_DESC VARCHAR,
	DEP_ATIVO BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
	FUN_MATRICULA SERIAL PRIMARY KEY,
	FUN_NOME VARCHAR NOT NULL,
	FUN_DEPARTAMENTO INT,
	FUN_TIPO INT,
	FUN_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT FK_TIPO_FUNCIONARIO FOREIGN KEY (FUN_TIPO) REFERENCES TIPO_FUNCIONARIO (T_ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (FUN_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DEP_CODIGO) ON UPDATE CASCADE ON DELETE SET DEFAULT
);

CREATE TABLE IF NOT EXISTS PERMISSOES (
	PERM_ID INT PRIMARY KEY,
	PERM_APPDEPARTAMENTO BOOLEAN NOT NULL,
	PERM_APPFUNCIONARIOS BOOLEAN NOT NULL,
	PERM_APPSOLICITACOES BOOLEAN NOT NULL,
	PERM_APPLOGS BOOLEAN NOT NULL,
	CONSTRAINT FK_TIPO_FUNCIONARIO FOREIGN KEY (PERM_ID) REFERENCES TIPO_FUNCIONARIO (T_ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS CREDENCIAIS (
	CRED_ID SERIAL PRIMARY KEY,
	CRED_LOGIN VARCHAR NOT NULL UNIQUE,
	CRED_SENHA VARCHAR NOT NULL,
	CRED_MATRICULA INT NOT NULL UNIQUE,
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (CRED_MATRICULA) REFERENCES FUNCIONARIO (FUN_MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APPS (
	APP_ID SERIAL PRIMARY KEY,
	APP_NOME VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS LOGS (
	LOG_ID SERIAL PRIMARY KEY,
	LOG_APP VARCHAR NOT NULL,
	LOG_TIPO VARCHAR NOT NULL,
	LOG_USER VARCHAR NOT NULL,
	LOG_CHANGES VARCHAR,
	CONSTRAINT FK_APPS FOREIGN KEY (LOG_APP) REFERENCES APPS (APP_NOME) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SOLICITACOES (
	SOLIC_ID SERIAL PRIMARY KEY,
	SOLIC_SOLICITANTE INT NOT NULL,
	SOLIC_DEPARTAMENTO INT,
	SOLIC_RESPONSAVEL INT NOT NULL,
	SOLIC_ASSUNTO VARCHAR NOT NULL,
	SOLIC_MSG VARCHAR,
	SOLIC_DATAINICIO DATE NOT NULL,
	SOLIC_DATAFIM DATE,
	SOLIC_ESTADO_TEMP VARCHAR NOT NULL,
	SOLIC_ESTADO_FINAL VARCHAR NOT NULL,
	CONSTRAINT FK_SOLIC_SOLICITANTE FOREIGN KEY (SOLIC_SOLICITANTE) REFERENCES FUNCIONARIO (FUN_MATRICULA) ON UPDATE CASCADE,
	CONSTRAINT FK_SOLIC_DEPARTAMENTO FOREIGN KEY (SOLIC_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DEP_CODIGO) ON UPDATE CASCADE ON DELETE SET DEFAULT,
	CONSTRAINT FK_RESPONSAVEL FOREIGN KEY (SOLIC_RESPONSAVEL) REFERENCES FUNCIONARIO (FUN_MATRICULA) ON UPDATE CASCADE,
	CONSTRAINT FK_CHECK_FIM_GEQ_INICIO CHECK (SOLIC_DATAFIM >= SOLIC_DATAINICIO)
);

-- CRIAR TIPOS DE FUNCIONARIOS (CONSIDERANDO FORMATAÇÃO DO JAVA EM UNICODE)
INSERT INTO TIPO_FUNCIONARIO (T_NOME) VALUES ('Superuser');
INSERT INTO TIPO_FUNCIONARIO (T_NOME) VALUES ('Diretor');
INSERT INTO TIPO_FUNCIONARIO (T_NOME) VALUES ('Chefe');
INSERT INTO TIPO_FUNCIONARIO (T_NOME) VALUES ('Funcionßrio');

-- CRIAR OS APLICATIVOS
INSERT INTO APPS (APP_NOME) VALUES ('Departamentos');
INSERT INTO APPS (APP_NOME) VALUES ('Funcionários');
INSERT INTO APPS (APP_NOME) VALUES ('Solicitações');
INSERT INTO APPS (APP_NOME) VALUES ('Logs');

-- DEFINIR PERMISSOES
INSERT INTO PERMISSOES (PERM_ID, PERM_APPLOGS, PERM_APPDEPARTAMENTO, PERM_APPFUNCIONARIOS, PERM_APPSOLICITACOES) VALUES (1, TRUE, TRUE, TRUE, TRUE);
INSERT INTO PERMISSOES (PERM_ID, PERM_APPLOGS, PERM_APPDEPARTAMENTO, PERM_APPFUNCIONARIOS, PERM_APPSOLICITACOES) VALUES (2, FALSE, TRUE, TRUE, TRUE);
INSERT INTO PERMISSOES (PERM_ID, PERM_APPLOGS, PERM_APPDEPARTAMENTO, PERM_APPFUNCIONARIOS, PERM_APPSOLICITACOES) VALUES (3, FALSE, FALSE, TRUE, TRUE);
INSERT INTO PERMISSOES (PERM_ID, PERM_APPLOGS, PERM_APPDEPARTAMENTO, PERM_APPFUNCIONARIOS, PERM_APPSOLICITACOES) VALUES (4, FALSE, FALSE, FALSE, TRUE);

-- CRIAR OS DEPARTAMENTOS 'PUBLICO', 'CONTROLE E MANUTENÇÃO DE BANCO DE DADOS', E 'DEPARTAMENTO DE TECNOLOGIA DA INFORMAÇÃO' (CONSIDERANDO FORMATAÇÃO DO JAVA EM UNICODE)
INSERT INTO DEPARTAMENTO (DEP_CODIGO, DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES (0, 'PUBLICO', 'Func. sem departamento', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DCMDB', 'Controle e Manut. de Banco de Dados', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DTI', 'Departamento de Tecnologia da InformaþÒo', TRUE);

-- CRIAR O SUPERUSER
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('SUPERUSER', 1, 1, TRUE);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('admin', 'admin', 1);

-- INSERIR DADOS DE TESTE PARA O BANCO (CONSIDERANDO FORMATAÇÃO DO JAVA EM UNICODE)
-- DEPARTAMENTOS
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DTES', 'Departamento de Tesouraria', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('GAB', 'Gabinete da Presidencia', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DADM', 'Departamento de AdministraþÒo', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DOC', 'Departamento de Obras Civis', TRUE);
INSERT INTO DEPARTAMENTO (DEP_SIGLA, DEP_DESC, DEP_ATIVO) VALUES ('DTRAN', 'Departamento de Transporte', FALSE); -- INATIVO

-- FUNCIONARIOS
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Lucas Oliveira', 4, 2, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Mariana Souza', 4, 2, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Carlos Silva', 2, 3, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Ana Costa', 3, 3, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Felipe Almeida', 5, 3, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Juliana Pereira', 6, 3, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Renato Gomes', 7, 3, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Fernanda Lima', 2, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Roberto Martins', 2, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Tatiane Rodrigues', 3, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Eduardo Santos', 3, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Isabela Fernandes', 5, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Pedro Almeida', 5, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Gabriela Nunes', 6, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Ricardo Castro', 6, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Mateus Costa', 7, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Bruno Santos', 7, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Camila Oliveira', 6, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Tatiane Almeida', 0, 4, TRUE); -- SEM DEPARTAMENTO
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Juliana Martins', 4, 4, TRUE);
INSERT INTO FUNCIONARIO (FUN_NOME, FUN_DEPARTAMENTO, FUN_TIPO, FUN_ATIVO) VALUES ('Ednaldo Pereira', 0, 4, FALSE); -- INATIVO

-- CREDENCIAIS
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('loliveira', '123', 2);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('msouza', '123', 3);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('csilva', '123', 4);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('acosta', '123', 5);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('falmeida', '123', 6);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('jpereira', '123', 7);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('rgomes', '123', 8);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('flima', '123', 9);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('rmartins', '123', 10);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('trodrigues', '123', 11);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('esantos', '123', 12);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('ifernandes', '123', 13);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('palmeida', '123', 14);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('gnunes', '123', 15);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('rcastro', '123', 16);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('mcosta', '123', 17);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('bsantos', '123', 18);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('coliveira', '123', 19);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('talmeida', '123', 20);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('jmartins', '123', 21);
INSERT INTO CREDENCIAIS (CRED_LOGIN, CRED_SENHA, CRED_MATRICULA) VALUES ('epereira', '123', 22);


